### ISSUE TITLE
SignatureController exception

### ISSUE THREAD

**Issue by payneBrandon** [usdot-jpo-ode/jpo-security-svcs#4]
When sending a message for signature, the SignatureController is attempting to read the `message-expiry` field from the returned data. This field is being returned from the HSM as a long, but on line 115 the SignatureController is attempting to read it as a string. This is causing the attached error.
[SecuritySVCS_Exception.txt](https://github.com/usdot-jpo-ode/jpo-security-svcs/files/5139089/SecuritySVCS_Exception.txt)

**Comment by jtbaird** [comment]
closed as part of ode release 1.2.0
